from __future__ import annotations
"""Generate C file from a object dictionary node for canfestival."""
"""Based on the original gen_cfile.py from odg"""
#
# Copyright (C) 2022-2024  Svein Seldal, Laerdal Medical AS
# Copyright (C) 2025-2025  Ronald Kaczynski, Laerdal Medical AS
# Copyright (C): Edouard TISSERANT, Francis DUPIN
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA

from generators_common import *
from pathlib import Path
from objdictgen.maps import OD
from objdictgen.typing import NodeProtocol, TPath

FILE_HEADER = """
/* File generated by gen_cfile.py. Should not be modified. */
"""

def generate_file_content(node: NodeProtocol, headerfile: str) -> tuple[str, str]:

    ctx, listindex, variablelist, communicationlist, valueRangeContent = setup_c_file_context(node)

    # --------------------------------------------------------------------------
    #        Creation of the mapped variables and object dictionary
    # --------------------------------------------------------------------------

    pointers_dict = {}
    sourceFileContent = ctx.text()
    pointedVariableContent = ctx.text()
    headerFileContent = ctx.text()
    indexContents: dict[int, str|Text] = {}

    def add_file_content(header_content, c_content):
        nonlocal headerFileContent
        nonlocal sourceFileContent

        #if "valueRange_" in typeinfos.ctype:
        #    ctx["subIndexType"] = "uint8_t"
        if typeinfos.ctype == "visible_string":
            ctx["subIndexType"] = "char"
        else:
            ctx["subIndexType"] = convert_from_canopen_to_c_type(typeinfos.ctype)

        headerFileContent %= header_content
        sourceFileContent %= c_content
        ctx["subIndexType"] = typeinfos.type

    for index in listindex:
        ctx["index"] = index
        entry_infos = node.GetEntryInfos(index)
        params_infos = node.GetParamsEntry(index)
        ctx["EntryName"] = entry_infos["name"]
        values = node.GetEntry(index)

        strindex = ctx.text()
        if index in variablelist:
            strindex %= "\n/* index 0x{index:04X} :   Mapped variable {EntryName} */\n"
        else:
            strindex %= "\n/* index 0x{index:04X} :   {EntryName}. */\n"

        # Entry type is VAR
        if not isinstance(values, list):
            # FIXME: It is assumed that the type of GetParamsEntry() follows the object type
            #        of GetEntry()
            assert not isinstance(params_infos, list)
            subentry_infos = node.GetSubentryInfos(index, 0)
            typename = node.GetTypeName(subentry_infos["type"])
            typeinfos = ctx.get_valid_type_infos(typename, [values])
            if typename == "DOMAIN" and index in variablelist:
                if not typeinfos.size:
                    raise ValueError(f"Domain variable not initialized, index: 0x{index:04X}, subindex: 0x00")
            ctx["subIndexType"] = typeinfos.type
            if typeinfos.size is not None:
                if params_infos["buffer_size"]:
                    ctx["suffix"] = f"[{params_infos['buffer_size']}]"
                else:
                    ctx["suffix"] = f"[{typeinfos.size}]"
            else:
                ctx["suffix"] = ""
            ctx["value"], ctx["comment"] = compute_value(values, typeinfos.ctype)
            if index in variablelist:
                ctx["name"] = RE_STARTS_WITH_DIGIT.sub(r'_\1', format_name(subentry_infos["name"]))
                add_file_content(
                (
                    "extern {subIndexType} {name}{suffix};"
                    "\t\t/* Mapped at index 0x{index:04X}, subindex 0x00*/\n"
                ),
                (
                    "{subIndexType} {name}{suffix} = {value};"
                    "\t\t/* Mapped at index 0x{index:04X}, subindex 0x00 */\n"
                ))
            else:
                strindex %= (
                    "                    "
                    "{subIndexType} {NodeName}_obj{index:04X}{suffix} = {value};{comment}\n"
                )
            values = [values]
        else:
            subentry_infos = node.GetSubentryInfos(index, 0)
            typename = node.GetTypeName(subentry_infos["type"])
            typeinfos = ctx.get_valid_type_infos(typename)
            ctx["value"] = values[0] if index != 0x1003 else 0
            ctx["subIndexType"] = typeinfos.type
            strindex %= (
                "                    "
                "{subIndexType} {NodeName}_highestSubIndex_obj{index:04X} = {value}; "
                "/* number of subindex - 1*/\n"
            )

            # Entry type is ARRAY
            if entry_infos["struct"] & OD.IdenticalSubindexes:
                subentry_infos = node.GetSubentryInfos(index, 1)
                typename = node.GetTypeName(subentry_infos["type"])
                typeinfos = ctx.get_valid_type_infos(typename, values[1:])
                ctx["subIndexType"] = typeinfos.type
                if typeinfos.size is not None:
                    ctx["suffix"] = f"[{typeinfos.size}]"
                    ctx["type_suffix"] = "*"
                else:
                    ctx["suffix"] = ""
                    ctx["type_suffix"] = ""
                ctx["length"] = values[0]
                if index in variablelist:
                    ctx["name"] = RE_STARTS_WITH_DIGIT.sub(r'_\1', format_name(entry_infos["name"]))
                    ctx["values_count"] = str(len(values) - 1)
                    add_file_content(
                    (
                        "extern {subIndexType} {name}[{values_count}]{suffix};\t\t"
                        "/* Mapped at index 0x{index:04X}, subindex 0x01 - 0x{length:02X} */\n"
                    ),
                    (
                        "{subIndexType} {name}[]{suffix} =\t\t"
                        "/* Mapped at index 0x{index:04X}, subindex 0x01 - 0x{length:02X} */\n  {{\n"
                    ))
                    for subindex, value in enumerate(values):
                        sep = ","
                        if subindex > 0:
                            if subindex == len(values) - 1:
                                sep = ""
                            value, comment = compute_value(value, typeinfos.ctype)
                            if len(value) == 2 and typename == "DOMAIN":
                                raise ValueError(
                                    "Domain variable not initialized, "
                                    f"index: 0x{index:04X}, subindex: 0x{subindex:02X}"
                                )
                            sourceFileContent += f"    {value}{sep}{comment}\n"
                    sourceFileContent += "  };\n"
                else:
                    strindex %= (
                        "                    "
                        "{subIndexType}{type_suffix} {NodeName}_obj{index:04X}[] = \n"
                        "                    {{\n"
                    )
                    for subindex, value in enumerate(values):
                        sep = ","
                        if subindex > 0:
                            if subindex == len(values) - 1:
                                sep = ""
                            value, comment = compute_value(value, typeinfos.ctype)
                            strindex += f"                      {value}{sep}{comment}\n"
                    strindex += "                    };\n"
            else:

                ctx["parent"] = RE_STARTS_WITH_DIGIT.sub(r'_\1', format_name(entry_infos["name"]))
                # Entry type is RECORD
                for subindex, value in enumerate(values):
                    ctx["subindex"] = subindex
                    # FIXME: Are there any point in calling this for subindex 0?
                    params_infos = node.GetParamsEntry(index, subindex)
                    # FIXME: Assumed params_info type is coherent with entry_infos["struct"]
                    assert not isinstance(params_infos, list)
                    if subindex > 0:
                        subentry_infos = node.GetSubentryInfos(index, subindex)
                        typename = node.GetTypeName(subentry_infos["type"])
                        typeinfos = ctx.get_valid_type_infos(typename, [values[subindex]])
                        ctx["subIndexType"] = typeinfos.type
                        if typeinfos.size is not None:
                            if params_infos["buffer_size"]:
                                ctx["suffix"] = f"[{params_infos['buffer_size']}]"
                            else:
                                ctx["suffix"] = f"[{typeinfos.size}]"
                        else:
                            ctx["suffix"] = ""
                        ctx["value"], ctx["comment"] = compute_value(value, typeinfos.ctype)
                        ctx["name"] = format_name(subentry_infos["name"])
                        if index in variablelist:
                            add_file_content(
                            (
                                "extern {subIndexType} {parent}_{name}{suffix};\t\t"
                                "/* Mapped at index 0x{index:04X}, subindex 0x{subindex:02X} */\n"
                            ),
                            (
                                "{subIndexType} {parent}_{name}{suffix} = {value};\t\t"
                                "/* Mapped at index 0x{index:04X}, subindex 0x{subindex:02X} */\n"
                            ))
                        else:
                            strindex %= (
                                "                    "
                                "{subIndexType} {NodeName}"
                                "_obj{index:04X}_{name}{suffix} = "
                                "{value};{comment}\n"
                            )

        # Generating Dictionary C++ entry
        strindex %= (
            "                    "
            "subindex {NodeName}_Index{index:04X}[] = \n"
            "                     {{\n"
        )
        generateSubIndexArrayComment = True
        for subindex, _ in enumerate(values):
            subentry_infos = node.GetSubentryInfos(index, subindex)
            params_infos = node.GetParamsEntry(index, subindex)
            # FIXME: As subindex is non-zero, params can't be a list
            assert not isinstance(params_infos, list)
            if subindex < len(values) - 1:
                sep = ","
            else:
                sep = ""
            typename = node.GetTypeName(subentry_infos["type"])
            if entry_infos["struct"] & OD.IdenticalSubindexes:
                typeinfos = ctx.get_valid_type_infos(typename, values[1:])
            else:
                typeinfos = ctx.get_valid_type_infos(typename, [values[subindex]])
            if subindex == 0:
                if index == 0x1003:
                    typeinfos = ctx.get_valid_type_infos("valueRange_EMC")
                if entry_infos["struct"] & OD.MultipleSubindexes:
                    name = f"{ctx['NodeName']}_highestSubIndex_obj{ctx['index']:04X}"
                elif index in variablelist:
                    name = format_name(subentry_infos["name"])
                else:
                    name = format_name(f"{ctx['NodeName']}_obj{ctx['index']:04X}")
            elif entry_infos["struct"] & OD.IdenticalSubindexes:
                if index in variablelist:
                    name = f"{format_name(entry_infos['name'])}[{subindex - 1}]"
                else:
                    name = f"{ctx['NodeName']}_obj{ctx['index']:04X}[{subindex - 1}]"
            else:
                if index in variablelist:
                    name = format_name(f"{entry_infos['name']}_{subentry_infos['name']}")
                else:
                    name = (
                        f"{ctx['NodeName']}_obj{ctx['index']:04X}_"
                        f"{format_name(subentry_infos['name'])}"
                    )
            if typeinfos.ctype == "visible_string":
                if params_infos["buffer_size"]:
                    sizeof = str(params_infos["buffer_size"])
                else:
                    value = values[subindex]
                    # FIXME: It should be a str type with visible_string
                    assert isinstance(value, str)
                    sizeof = str(max(len(value), ctx.default_string_size))
            elif typeinfos.ctype == "domain":
                value = values[subindex]
                # FIXME: Value should be string
                assert isinstance(value, str)
                sizeof = str(len(value))
            else:
                sizeof = f"sizeof ({typeinfos.type})"
            params = node.GetParamsEntry(index, subindex)
            # FIXME: As subindex is non-zero, params can't be a list
            assert not isinstance(params, list)
            if params["save"]:
                save = "|TO_BE_SAVE"
            else:
                save = ""
            start_digit = RE_STARTS_WITH_DIGIT.sub(r'_\1', name)
            strindex += (
                f"                       {{ "
                f"{subentry_infos['access'].upper()}{save}, "
                f"{typeinfos.ctype}, {sizeof}, (void*)&{start_digit}, NULL "
                f"}}{sep}\n"
            )
            pointer_name = pointers_dict.get((index, subindex), None)
            if pointer_name is not None:
                pointedVariableContent += f"{typeinfos.type}* {pointer_name} = &{name};\n"
        strindex += "                     };\n"
        indexContents[index] = strindex

    # --------------------------------------------------------------------------
    #                 Declaration of Particular Parameters
    # --------------------------------------------------------------------------

    if 0x1003 not in communicationlist:
        entry_infos = node.GetEntryInfos(0x1003)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1003] = ctx.ftext("""
/* index 0x1003 :   {EntryName} */
                    UNS8 {NodeName}_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 {NodeName}_obj1003[] =
                    {{
                      0x0	/* 0 */
                    }};
                    subindex {NodeName}_Index1003[] =
                     {{
                       {{ RW, valueRange_EMC, sizeof (UNS8), (void*)&{NodeName}_highestSubIndex_obj1003, NULL }},
                       {{ RO, uint32, sizeof (UNS32), (void*)&{NodeName}_obj1003[0], NULL }}
                     }};
""")

    if 0x1005 not in communicationlist:
        entry_infos = node.GetEntryInfos(0x1005)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1005] = ctx.ftext("""
/* index 0x1005 :   {EntryName} */
                    UNS32 {NodeName}_obj1005 = 0x0;   /* 0 */
""")

    if 0x1006 not in communicationlist:
        entry_infos = node.GetEntryInfos(0x1006)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1006] = ctx.ftext("""
/* index 0x1006 :   {EntryName} */
                    UNS32 {NodeName}_obj1006 = 0x0;   /* 0 */
""")

    if 0x1014 not in communicationlist:
        entry_infos = node.GetEntryInfos(0x1014)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1014] = ctx.ftext("""
/* index 0x1014 :   {EntryName} */
                    UNS32 {NodeName}_obj1014 = 0x80 + 0x{NodeID:02X};   /* 128 + NodeID */
""")

    if 0x1016 in communicationlist:
        hbn = node.GetEntry(0x1016, 0)
        # FIXME: Hardcoded assumption on data-type?
        assert isinstance(hbn, int)
        ctx["heartBeatTimers_number"] = hbn
    else:
        ctx["heartBeatTimers_number"] = 0
        entry_infos = node.GetEntryInfos(0x1016)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1016] = ctx.ftext("""
/* index 0x1016 :   {EntryName} */
                    UNS8 {NodeName}_highestSubIndex_obj1016 = 0;
                    UNS32 {NodeName}_obj1016[]={{0}};
""")

    if 0x1017 not in communicationlist:
        entry_infos = node.GetEntryInfos(0x1017)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x1017] = ctx.ftext("""
/* index 0x1017 :   {EntryName} */
                    UNS16 {NodeName}_obj1017 = 0x0;   /* 0 */
""")

    if 0x100C not in communicationlist:
        entry_infos = node.GetEntryInfos(0x100C)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x100C] = ctx.ftext("""
/* index 0x100C :   {EntryName} */
                    UNS16 {NodeName}_obj100C = 0x0;   /* 0 */
""")

    if 0x100D not in communicationlist:
        entry_infos = node.GetEntryInfos(0x100D)
        ctx["EntryName"] = entry_infos["name"]
        indexContents[0x100D] = ctx.ftext("""
/* index 0x100D :   {EntryName} */
                    UNS8 {NodeName}_obj100D = 0x0;   /* 0 */
""")

    # --------------------------------------------------------------------------
    #           Declaration of navigation in the Object Dictionary
    # --------------------------------------------------------------------------

    strDeclareIndex = ctx.text()
    strDeclareSwitch = ""
    strQuickIndex = ""

    quick_index: dict[str, dict[str, int]] = {}
    for index_cat in INDEX_CATEGORIES:
        quick_index[index_cat] = {}
        for cat, idx_min, idx_max in CATEGORIES:
            quick_index[index_cat][cat] = 0

    maxPDOtransmit = 0
    for i, index in enumerate(listindex):
        ctx["index"] = index
        strDeclareIndex %= (
            "  {{ (subindex*){NodeName}_Index{index:04X},"
            "sizeof({NodeName}_Index{index:04X})/"
            "sizeof({NodeName}_Index{index:04X}[0]), 0x{index:04X}}},\n"
        )
        strDeclareSwitch += f"       case 0x{index:04X}: i = {i};break;\n"
        for cat, idx_min, idx_max in CATEGORIES:
            if idx_min <= index <= idx_max:
                quick_index["lastIndex"][cat] = i
                if quick_index["firstIndex"][cat] == 0:
                    quick_index["firstIndex"][cat] = i
                if cat == "PDO_TRS":
                    maxPDOtransmit += 1

    ctx["maxPDOtransmit"] = max(1, maxPDOtransmit)
    for index_cat in INDEX_CATEGORIES:
        strQuickIndex += f"\nconst quick_index {ctx['NodeName']}_{index_cat} = {{\n"
        sep = ","
        for i, (cat, idx_min, idx_max) in enumerate(CATEGORIES):
            if i == len(CATEGORIES) - 1:
                sep = ""
            strQuickIndex += f"  {quick_index[index_cat][cat]}{sep} /* {cat} */\n"
        strQuickIndex += "};\n"

    # --------------------------------------------------------------------------
    #                        Write Constants File Content
    # --------------------------------------------------------------------------

    constantsFileContent = ctx.text(FILE_HEADER)
    constantsFileContent += f"""
#include "{headerfile.replace(".h", "Constants.h")}"
/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
"""
    constantsFileContent += sourceFileContent


    # --------------------------------------------------------------------------
    #                        Write File Content
    # --------------------------------------------------------------------------
    fileContent = ctx.text(FILE_HEADER)
    fileContent += f"""
#include "{headerfile}"
#include "data.h"
"""

    fileContent %= """
/* Prototypes of function provided by object dictionnary */
UNS32 {NodeName}_valueRangeTest (UNS8 typeValue, void * value);
const indextable * {NodeName}_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);
"""

    fileContent += """
/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/
"""
    fileContent += valueRangeContent
    fileContent %= """
/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 {NodeName}_bDeviceNodeId = 0x{NodeID:02X};

/**************************************************************************/
/* Array of message processing information */

const UNS8 {NodeName}_iam_a_slave = {iam_a_slave};

"""
    if ctx["heartBeatTimers_number"] > 0:
        declaration = ctx.ftext(
            "TIMER_HANDLE {NodeName}_heartBeatTimers[{heartBeatTimers_number}]"
        )
        initializer = "{TIMER_NONE" + ",TIMER_NONE" * (ctx["heartBeatTimers_number"] - 1) + "}"
        fileContent += declaration + " = " + initializer + ";\n"
    else:
        fileContent += f"TIMER_HANDLE {ctx['NodeName']}_heartBeatTimers[1];\n"

    fileContent += """
/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/
"""
    for index in sorted(indexContents):
        fileContent += indexContents[index]

    fileContent += """
/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/
"""
    fileContent += pointedVariableContent
    fileContent %= """
const indextable {NodeName}_objdict[] =
{{
"""
    fileContent += strDeclareIndex
    fileContent %= """}};

const indextable * {NodeName}_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{{
    int i;
    (void)d; /* unused parameter */
    switch(wIndex){{
"""
    fileContent += strDeclareSwitch
    fileContent %= """       default:
            *errorCode = OD_NO_SUCH_OBJECT;
            return NULL;
    }}
    *errorCode = OD_SUCCESSFUL;
    return &{NodeName}_objdict[i];
}}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status {NodeName}_PDO_status[{maxPDOtransmit}] = {{"""

    fileContent += ",".join(["s_PDO_status_Initializer"] * ctx["maxPDOtransmit"]) + "};\n"
    fileContent += strQuickIndex
    fileContent %= """
const UNS16 {NodeName}_ObjdictSize = sizeof({NodeName}_objdict)/sizeof({NodeName}_objdict[0]);

CO_Data {NodeName}_Data = CANOPEN_NODE_DATA_INITIALIZER({NodeName});

"""


    fileContent += """
// unsigned
static_assert(sizeof(UNS8) == sizeof(uint8_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS16) == sizeof(uint16_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS24) == sizeof(uint32_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS32) == sizeof(uint32_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS40) == sizeof(uint64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS48) == sizeof(uint64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS56) == sizeof(uint64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(UNS64) == sizeof(uint64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
// signed
static_assert(sizeof(INTEGER8) == sizeof(int8_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER16) == sizeof(int16_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER24) == sizeof(int32_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER32) == sizeof(int32_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER40) == sizeof(int64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER48) == sizeof(int64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER56) == sizeof(int64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
static_assert(sizeof(INTEGER64) == sizeof(int64_t), "Error: canfestival and std type size mismatch -- fix .py generator");
"""

    # --------------------------------------------------------------------------
    #                      Write Header File Content
    # --------------------------------------------------------------------------

    ctx["file_include_name"] = headerfile.replace(".", "_").upper()
    header = ctx.text(FILE_HEADER)
    header %= """
#ifndef {file_include_name}
#define {file_include_name}

#include <cstdint>

/* Master node data struct */
typedef struct struct_CO_Data CO_Data;
extern CO_Data {NodeName}_Data;\n
"""
    header %= "\n#endif // {file_include_name}\n"

    # --------------------------------------------------------------------------
    #                      Write Header File Constants Content
    # --------------------------------------------------------------------------

    headerfile = headerfile.replace(".h", "Constants.h")
    ctx["file_include_name"] = headerfile.replace(".", "_").upper()
    constantsHeader = ctx.text(FILE_HEADER)
    constantsHeader %= """
#ifndef {file_include_name}
#define {file_include_name}

#include <cstdint>

/* Master node data struct */
"""
    constantsHeader += headerFileContent
    constantsHeader %= "\n#endif // {file_include_name}\n"

    return str(fileContent), str(header), str(constantsFileContent), str(constantsHeader)


# ------------------------------------------------------------------------------
#                             Main Function
# ------------------------------------------------------------------------------

def GenerateFile(filepath: TPath, node: NodeProtocol, pointers_dict=None):
    """Main function to generate the C file from a object dictionary node."""
    filepath = Path(filepath)
    headerpath = filepath.with_suffix(".h")
    constantsPath = Path(filepath.stem + "Constants").with_suffix(".cpp")
    constantsHeaderPath = constantsPath.with_suffix(".h")
    print(constantsPath, constantsHeaderPath)
    content, header, constantsContent, constantsHeader = generate_file_content(
        node, headerpath.name,
    )
    # Write main .c contents
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    with open(headerpath, "w", encoding="utf-8") as f:
        f.write(header)

    # write constants
    with open(constantsPath, "w", encoding="utf-8") as f:
        f.write(constantsContent)

    with open(constantsHeaderPath, "w", encoding="utf-8") as f:
        f.write(constantsHeader)
